# Generated by Django 4.2.1 on 2023-05-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_detailsjson_json_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsjson',
            name='json_detail',
            field=models.JSONField(),
        ),
    ]
