# Generated by Django 4.2.1 on 2023-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_detailsjson_json_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsjson',
            name='json_detail',
            field=models.TextField(max_length=5000),
        ),
    ]
