# Generated by Django 4.2.1 on 2023-05-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_detailsjson_json_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailsJson',
            new_name='DetailsJsonModel',
        ),
    ]
