# Generated by Django 4.2.1 on 2023-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_rename_detailsjsonmodel_scrapeddatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_edu', models.JSONField()),
            ],
        ),
    ]
